language: python
sudo: false
cache:
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
    - $YT_DIR
    - $YTREE_DATA
  pip: true

addons:
  apt:
    packages:
      - libhdf5-serial-dev

env:
  global:
    NUMPY=numpy
    CYTHON=cython
    MATPLOTLIB=matplotlib
    SYMPY=sympy
    H5PY=h5py
    SCIPY=scipy
    IPYTHON=ipython
    FASTCACHE=fastcache
    YT_DIR=$HOME/yt-git
    YTREE_DATA=$HOME/ytree_test

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6

before_install:
  - |
    export PATH=/usr/lib/ccache:$PATH
    # configure ytree
    mkdir -p $HOME/.config/ytree
    echo "[ytree]" > $HOME/.config/ytree/ytreerc
    echo "test_data_dir = $YTREE_DATA" >> $HOME/.config/ytree/ytreerc
    cat $HOME/.config/ytree/ytreerc

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    # Install dependencies
    pip install mock $NUMPY $SCIPY $H5PY $CYTHON $MATPLOTLIB $SYMPY $FASTCACHE $IPYTHON flake8 pytest girder-client
    # install yt
    if [ ! -f $YT_DIR/README.md ]; then
        git clone --branch=master https://github.com/yt-project/yt $YT_DIR
    fi
    pushd $YT_DIR
    git pull
    git checkout master
    pip install -e .
    popd
    # install ytree
    pip install -e .

before_script:
  - |
    # download test data
    if [ ! -d $YTREE_DATA/rockstar ]; then
        girder-cli --api-url https://girder.hub.yt/api/v1 download 59835a1ee2a67400016a2cda $YTREE_DATA
    fi

script:
  - |
    travis_wait 20 pytest tests
