language: python
sudo: false
cache:
  directories:
    - $HOME/ytree_test
    - $HOME/yt-git
  pip: true

addons:
  apt:
    packages:
      - libhdf5-serial-dev

env:
  global:
    NUMPY=numpy
    CYTHON=cython
    MATPLOTLIB=matplotlib
    SYMPY=sympy
    H5PY=h5py
    SCIPY=scipy
    IPYTHON=ipython
    FASTCACHE=fastcache

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6

before_install:
  - |
    mkdir -p $HOME/.config/ytree
    echo "[ytree]" > $HOME/.config/ytree/ytreerc
    echo "test_data_dir = $HOME/ytree_test" >> $HOME/.config/ytree/ytreerc
    cat $HOME/.config/ytree/ytreerc

install:
  - |
    # Upgrade pip and setuptools and wheel to get clean install
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    # Install dependencies
    pip install mock $NUMPY $SCIPY $H5PY $CYTHON $MATPLOTLIB $SYMPY $FASTCACHE $IPYTHON flake8 pytest girder-client
    # install yt
    if [ -d $HOME/yt-git/README.md ]; then
        git pull
    else
        git clone https://github.com/yt-project/yt $HOME/yt-git
    fi
    pushd $HOME/yt-git
    pip install -e .
    popd
    # install ytree
    pip install -e .

before_script:
  - |
    # download test data
    .travis_scripts/download_test_data.sh

script:
  - |
    pytest tests
