name: ytree
dependencies:
  - cython=0.28.2
  - numpy=1.14.2
  - pip=9.0.3=py36_0
  - python=3.6.5
  - setuptools=39.0.1=py36_0
  - wheel=0.31.0
  - pip:
    - appnope==0.1.0
    - backcall==0.1.0
    - configparser==3.5.0
    - cycler==0.10.0
    - decorator==4.3.0
    - h5py==2.7.1
    - ipython==6.3.1
    - ipython-genutils==0.2.0
    - jedi==0.12.0
    - kiwisolver==1.0.1
    - matplotlib==2.2.2
    - mpmath==1.0.0
    - parso==0.2.0
    - pexpect==4.5.0
    - pickleshare==0.7.4
    - prompt-toolkit==1.0.15
    - ptyprocess==0.5.2
    - pygments==2.2.0
    - pyparsing==2.2.0
    - python-dateutil==2.7.2
    - pytz==2018.4
    - simplegeneric==0.8.1
    - six==1.11.0
    - sympy==1.1.1
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - yt==3.4.1
